#!/usr/bin/env python3
"""Generate sram_32x8_9T's structural (gate-level) netlist.

LibreLane's per-macro `nl` field must hold "valid Verilog netlists readable
by tools such as OpenSTA" (librelane/config/variable.py, Macro.nl) -- paired
with `spef`, it enables SPEF-based hierarchical STA instead of treating the
macro as a pure Liberty black box. OpenSTA resolves each instantiated cell's
timing from a linked Liberty model, so this can't be either of the two
Verilog views that already exist in ../vh/: the transistor-level SPICE
netlist (pex/sram_32x8_9T.spice) has no cell/Liberty concept OpenSTA could
use, and the behavioral model (sram_32x8_9T.v) has no instances at all.

sram_32x8_9T really is a tiled array of one physical cell
(../mag/9T_tileable.mag, real layout) -- so the correct structural
representation is what's built here: 256 instances of sram_bitcell_9T
(../lib/gen_bitcell_lib.py's real per-cell Liberty model), wired per the
same row/column indexing already validated in ../vh/sram_32x8_9T.v against
the real extracted SPICE behavior (RBL[r*8+c] = mem[r][c] & A[r]; WL/A are
per-row, WBL/WBLB per-column). Q/QB (the per-cell storage nodes) aren't
array-level ports and aren't in sram_bitcell_9T's Liberty pin list, so they
aren't wired here either -- left as the tool default (unconnected).

The file also defines sram_bitcell_9T itself, as an empty/blackbox-style
module (port list only, matching the Liberty pin list exactly), so the
netlist is self-contained rather than referencing an undefined module 256
times. A real transistor-level body isn't an option: it's exactly what was
ruled out above (OpenSTA can't resolve timing through pmos/nmos primitives,
which is the whole reason this file is hierarchical instead of flattened).
The empty body is intentional, not a placeholder -- sram_bitcell_9T's
actual timing/loading always comes from the paired .lib, the same way a
real synthesized netlist's standard-cell instances carry no Verilog body
of their own either.
"""
from pathlib import Path

HERE = Path(__file__).resolve().parent
OUT = HERE / "sram_32x8_9T.nl.v"

ROWS = 32
COLS = 8

with open(OUT, "w") as f:
    f.write("/*\n")
    f.write(" * sram_32x8_9T -- structural netlist for SPEF-based hierarchical STA\n")
    f.write(" * Generated by gen_nl.py. 256 x sram_bitcell_9T (real tiled layout,\n")
    f.write(" * see gen_nl.py's docstring). Timing arcs come from\n")
    f.write(" * ../lib/sram_bitcell_9T__tt_025C_3v30.lib, not from this file.\n")
    f.write(" */\n\n")

    # Port list matches sram_bitcell_9T__tt_025C_3v30.lib's pin list exactly
    # (gen_bitcell_lib.py) -- empty body, timing/loading comes from the
    # paired .lib, not from this netlist (see module docstring).
    f.write("module sram_bitcell_9T (\n")
    f.write("    input A,\n")
    f.write("    input WL,\n")
    f.write("    input WBL,\n")
    f.write("    input WBLB,\n")
    f.write("    output RBL,\n")
    f.write("    inout VDD,\n")
    f.write("    inout VSS\n")
    f.write(");\n")
    f.write("// Leave empty so OpenROAD knows the pins exist\n")
    f.write("endmodule\n\n")

    f.write("module sram_32x8_9T (\n")
    f.write("    WL,\n    A,\n    WBL,\n    WBLB,\n    RBL,\n    VDD,\n    VSS\n")
    f.write(");\n")
    f.write(f"input  [{ROWS-1}:0]  WL;\n")
    f.write(f"input  [{ROWS-1}:0]  A;\n")
    f.write(f"input  [{COLS-1}:0]   WBL;\n")
    f.write(f"input  [{COLS-1}:0]   WBLB;\n")
    f.write(f"output [{ROWS*COLS-1}:0] RBL;\n")
    f.write("inout VDD;\n")
    f.write("inout VSS;\n\n")

    for r in range(ROWS):
        for c in range(COLS):
            k = r * COLS + c
            f.write(
                f"sram_bitcell_9T bit_r{r}_c{c} "
                f"( .A(A[{r}]), .WL(WL[{r}]), .WBL(WBL[{c}]), .WBLB(WBLB[{c}]), "
                f".RBL(RBL[{k}]), .VDD(VDD), .VSS(VSS) );\n"
            )

    f.write("\nendmodule\n")

print(f"wrote {OUT}")
print(f"{ROWS * COLS} sram_bitcell_9T instances, wired per real row/column indexing "
      f"(matches ../vh/sram_32x8_9T.v)")
